services:
  - type: web
    name: dsdsasdasaddsa
    runtime: python
    plan: starter
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true; find . -name '*.pyc' -delete 2>/dev/null || true; python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
